### ISSUE TITLE
bro really?

### ISSUE THREAD

**Issue by Cl1ckerr** [xsplitst/RblxWild-Auto-Rain-Joiner#1]
![image](https://user-images.githubusercontent.com/75802182/178496641-76d01cc2-d6a0-4c80-bac8-ccf04127dc56.png)

**Comment by Nepzerox** [comment]
the biggest brain

**Comment by Cl1ckerr** [comment]
![image](https://user-images.githubusercontent.com/75802182/178779068-8301dbf4-f1d4-4814-9398-ad2e986302db.png)
dont steal my stealer 😜

**Comment by zLeki** [comment]
don't steal the compiled executable oh no
